<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Kenboy\YandexCheckout\Block\Form $block */

$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none"
>
    <div class="admin__field _required">
        <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_type" >
            <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
        </label>
        <div class="admin__field-control control">
            <select id="<?= /* @noEscape */ $code ?>_cc_type" name="payment[cc_type]"
                    class="required-entry select admin__control-select validate-cc-type-select"
                    data-validate="{
                        'required':true,
                        'validate-cc-type-select':'#<?= /* @noEscape */ $code ?>_cc_number'
                        }"
            >
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $block->escapeHtml($typeCode) ?>"
                        <?php if($typeCode == $ccType): ?> selected="selected"<?php endif; ?>>
                        <?= $block->escapeHtml($typeName) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="admin__field _required">
        <label for="<?= /* @noEscape */ $code ?>_cc_number" class="label admin__field-label">
            <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="admin__field-control control">
            <input type="text" id="<?= /* @noEscape */ $code ?>_cc_number"
                   name="payment[cc_number]"
                   data-validate="{
                       'required-number':true,
                       'validate-cc-number':'#<?= /* @noEscape */ $code ?>_cc_type',
                       'validate-cc-type':'#<?= /* @noEscape */ $code ?>_cc_type'
                   }"
                   class="admin__control-text"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_number') ?>"/>
        </div>
    </div>

    <div class="admin__field _required">
        <label for="<?= /* @noEscape */ $code ?>_expiration" class="label admin__field-label">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="admin__field-control control">
            <select id="<?= /* @noEscape */ $code ?>_expiration"
                    name="payment[cc_exp_month]"
                    class="admin__control-select admin__control-select-month"
                    data-validate="{
                        'required':true,
                        'validate-cc-exp':'#<?= /* @noEscape */ $code ?>_expiration_yr'
                        }">
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?= $block->escapeHtml($k) ?>"
                            <?php if ($k == $block->getInfoData('cc_exp_month')): ?>selected="selected"<?php endif; ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?= /* @noEscape */ $code ?>_expiration_yr"
                    name="payment[cc_exp_year]"
                    class="admin__control-select admin__control-select-year"
                    data-container="<?= /* @noEscape */ $code ?>-cc-year"
                    data-validate="{required:true}">
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                            <?php if ($k == $block->getInfoData('cc_exp_year')): ?>selected="selected"<?php endif; ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <?php if($block->hasVerification()): ?>
        <div class="admin__field _required field-cvv">
            <label class="label admin__field-label"
                   for="<?= /* @noEscape */ $code ?>_cc_cid"
                   id="<?= /* @noEscape */ $code ?>_cc_type_cvv_div"
            >
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="admin__field-control control">
                <input type="text"
                       data-container="<?= /* @noEscape */ $code ?>-cc-cvv"
                       title="<?= $block->escapeHtml(__('Card Verification Number')) ?>"
                       class="admin__control-text cvv"
                       id="<?= /* @noEscape */ $code ?>_cc_cid" name="payment[cc_cid]"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_cid') ?>"
                       data-validate="{
                           'required-number':true,
                           'validate-cc-cvn':'#<?= /* @noEscape */ $code ?>_cc_type'
                       }"
                       autocomplete="off"/>
            </div>
        </div>
    <?php endif; ?>

    <?php if($block->isVaultEnabled()): ?>
        <div class="field-tooltip-content">
            <input type="checkbox"
                   id="<?= /* @noEscape */ $code ?>_vault"
                   name="payment[is_active_payment_token_enabler]"
                   class="admin__control-checkbox"/>
            <label class="label" for="<?= /* @noEscape */ $code ?>_vault">
                <span><?= $block->escapeHtml('Save for later use.') ?></span>
            </label>
        </div>
    <?php endif; ?>

    <input type="hidden" id="<?= /* @noEscape */ $code ?>_payment_method_nonce"
           name="payment[payment_method_nonce]"/>
    <input type="submit" name="Submit" style="display: none;">
</fieldset>
